# Generated by Django 5.1.1 on 2025-08-06 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_id', models.CharField(max_length=255)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.assistant')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('openai_thread_id', models.CharField(max_length=255)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='core.assistant')),
            ],
        ),
    ]
